= Configuration

Elasticsearch is an open source, highly scalable, full-text search and analytics
engine.

By default, Elasticsearch runs as an embedded search engine, but it's only
supported in production as a separate server or cluster. This guide walks you
through the process of configuring Elasticsearch.

If you'd rather use Solr, it's also supported. See the documentation on
Installing Solr if you're interested.

////
See [here](discover/deployment/-/knowledge_base/7-1/using-solr) for information
on installing and configuring Solr.
////

To get up and running quickly with Elasticsearch as a remote server, refer to
the link:/discover/deployment/-/knowledge_base/7-1/installing-elasticsearch[Installing Elasticsearch article].
Those are basic instructions for installing and configuring Elasticsearch in
a single server environment. This article includes more details and information
on clustering and tuning Elasticsearch. Here, you'll learn to configure your
existing Elasticsearch installation for use in production environments.

If you've come here looking for information on search engines in general, or the
low level search infrastructure of @product@, refer instead to the developer
tutorial
Introduction to Liferay Search (not yet written).

These terms are useful to understand as you read this guide:

* _Elasticsearch Home_ refers to the root folder of your unzipped Elasticsearch
installation (for example, `elasticsearch-6.1.3`).
* link:/discover/deployment/-/knowledge_base/7-1/installing-liferay#liferay-home[_Liferay Home_]
refers to the root folder of your @product@ installation. It contains the
`osgi`, `deploy`, `data`, and `license` folders, among others.


