= Installing @product@ on Tomcat 

If you can not or don't want to use the @product@ bundle, you can install it on existing Tomcat server.

You need to download the following files from https://www.liferay.com/downloads-community[]

* @product@ WAR file
* Dependencies ZIP file
* OSGi JARs ZIP file

Here are the basic steps for installing @product@ on Tomcat:

== Dependencies

@product@ depends on many JARs included by @product@ Tomcat bundle. Some of the
bundle's JARs are not strictly required but can still be useful. If you don't
have a bundle, download the required JARs from third-parties, as described
below.

. Create the folder `$TOMCAT_HOME/lib/ext` if it doesn't exist and extract the
JARs from the dependencies ZIP to it. Here are the JARs:
    * `com.liferay.petra.concurrent.jar`
    * `com.liferay.petra.executor.jar`
    * `com.liferay.petra.function.jar`
    * `com.liferay.petra.io.jar`
    * `com.liferay.petra.lang.jar`
    * `com.liferay.petra.memory.jar`
    * `com.liferay.petra.nio.jar`
    * `com.liferay.petra.process.jar`
    * `com.liferay.petra.process.jar`
    * `com.liferay.petra.reflect.jar`
    * `com.liferay.petra.string.jar`
    * `com.liferay.registry.api.jar`
    * `hsql.jar`
    * `portal-kernel.jar`
    * `portlet.jar`
. Download the following JARs or copy them from a @product@ Tomcat bundle to
the `$TOMCAT_HOME/lib/ext` folder:
    * http://www.oracle.com/technetwork/java/javase/jaf-136260.html[`activation.jar`]
    * http://mvnrepository.com/artifact/javax.ccpp/ccpp/1.0[`ccpp.jar`]
    * http://www.oracle.com/technetwork/java/docs-136352.html[`jms.jar`]
    * http://www.oracle.com/technetwork/java/javaee/jta/index.html[`jta.jar`]
    * http://mvnrepository.com/artifact/com.beetstra.jutf7/jutf7[`jutf7.jar`]
    * http://www.oracle.com/technetwork/java/index-138643.html[`mail.jar`]
    * http://mvnrepository.com/artifact/org.eclipse.persistence/javax.persistence/2.1.1[`persistence.jar`]
    * http://mvnrepository.com/artifact/com.liferay.portal/com.liferay.support.tomcat[`support-tomcat.jar`]
. Copy the JDBC driver for your database to the `$CATALINA_BASE/lib/ext`
folder. Here are some common drivers:
    * https://downloads.mariadb.org/[`mariadb.jar`]
    * http://dev.mysql.com/downloads/connector/j[`mysql.jar`]
    * https://jdbc.postgresql.org/download/postgresql-42.0.0.jar[`postgresql.jar`]
. Create an `osgi` folder in your Liferay Home. Extract the folders (i.e.,
`configs`, `core`, and more) from OSGi ZIP file to the `osgi` folder. The
`osgi` folder provides the necessary modules for @product@'s OSGi runtime.

=== Checkpoint

. Your `$CATALINA_BASE/lib/ext` folder has these JARs:
    * `activation.jar`
    * `ccpp.jar`
    * `com.liferay.petra.concurrent.jar`
    * `com.liferay.petra.executor.jar`
    * `com.liferay.petra.function.jar`
    * `com.liferay.petra.io.jar`
    * `com.liferay.petra.lang.jar`
    * `com.liferay.petra.memory.jar`
    * `com.liferay.petra.nio.jar`
    * `com.liferay.petra.process.jar`
    * `com.liferay.petra.reflect.jar`
    * `com.liferay.petra.string.jar`
    * `com.liferay.registry.api.jar`
    * `hsql.jar`
    * `jms.jar`
    * `jta.jar`
    * `jutf7.jar`
    * `mail.jar`
    * `mariadb.jar`
    * `mysql.jar`
    * `persistence.jar`
    * `portal-kernel.jar`
    * `portlet.jar`
    * `postgresql.jar`
    * `support-tomcat.jar`
. Your `[Liferay Home]/osgi` folder has these subfolders:
    * `configs`
    * `core`
    * `marketplace`
    * `modules`
    * `portal`
    * `static`
    * `test`
    * `war`

== Tomcat configuration

=== Environment variables

If you have a @product@ Tomcat bundle, copy the `setenv.bat` and `setenv.sh` files from it to your `$CATALINA_BASE/bin` folder. If not, create these scripts.

The scripts set JVM options for Catalina, which is Tomcat's servlet container. Among these options is the location of the Java runtime environment. If this environment is not available on your server globally, you must set its location in in these files so Tomcat can run. Do this by pointing the `JAVA_HOME` environment variable to a @product@-supported JRE:

    export JAVA_HOME=/usr/lib/jvm/java-8-jdk
    export PATH=$JAVA_HOME/bin:$PATH

=== JVM options

Configure Catalina's JVM options to support @product@.

Unix:

    CATALINA_OPTS="$CATALINA_OPTS -Dfile.encoding=UTF8 -Djava.net.preferIPv4Stack=true -Dorg.apache.catalina.loader.WebappClassLoader.ENABLE_CLEAR_REFERENCES=false -Duser.timezone=GMT -Xmx2048m -XX:MaxMetaspaceSize=512m"

Windows:

    set "CATALINA_OPTS=%CATALINA_OPTS% -Dfile.encoding=UTF8 -Djava.net.preferIPv4Stack=true -Dorg.apache.catalina.loader.WebappClassLoader.ENABLE_CLEAR_REFERENCES=false -Duser.timezone=GMT -Xmx2048m -XX:MaxMetaspaceSize=512m"

This sets the file encoding to UTF-8, prefers an IPv4 stack over IPv6, prevents Tomcat from working around garbage collection bugs relating to
static or final fields (these bugs don't exist in @product@ and working around them causes problems with the logging system), sets the time zone to GMT, gives the JVM 2GB of RAM, and limits Metaspace to 500MB.

=== ROOT.xml

The `ROOT.xml` file specifies a web application context for @product@.

If you have a @product@ Tomcat bundle, copy its `$CATALINA_BASE/conf/Catalina/localhost/ROOT.xml` file to the corresponding location in your application server. Create the file path if it doesn't exist. If you don't have a @product@ Tomcat bundle, create a `ROOT.xml` file:

.ROOT.xml
[source,xml]
----
<Context crossContext="true" path="">

    <!-- JAAS -->

    <!--<Realm
        className="org.apache.catalina.realm.JAASRealm"
        appName="PortalRealm"
        userClassNames="com.liferay.portal.kernel.security.jaas.PortalPrincipal"
        roleClassNames="com.liferay.portal.kernel.security.jaas.PortalRole"
    />-->

    <!--
    Uncomment the following to disable persistent sessions across reboots.
    -->

    <!--<Manager pathname="" />-->

    <!--
    Uncomment the following to not use sessions. See the property
    "session.disabled" in portal.properties.
    -->

    <!--<Manager className="com.liferay.support.tomcat.session.SessionLessManagerBase" />-->

    <Resources>
        <PreResources
            base="${catalina.base}/lib/ext/portal"
            className="com.liferay.support.tomcat.webresources.ExtResourceSet"
            webAppMount="/WEB-INF/lib"
        />
    </Resources>
</Context>
----

Setting `crossContext="true"` lets multiple web applications use the same class loader. This configuration includes commented instructions and tags for configuring a JAAS realm, disabling persistent sessions, and disabling sessions entirely.

=== Ext JAR files

Provide Catalina access to the JARs in `$CATALINA_BASE/lib/ext` by opening your `$CATALINA_BASE/conf/catalina.properties` file and appending this value to the `common.loader` property:

    ,"${catalina.home}/lib/ext/global","${catalina.home}/lib/ext/global/*.jar","${catalina.home}/lib/ext","${catalina.home}/lib/ext/*.jar"

=== UTF-8 

Make sure to use UTF-8 URI encoding consistently. If you have a @product@ Tomcat bundle, copy the `$CATALINA_BASE/conf/server.xml` file to your
server. If not, open your `$CATALINA_BASE/conf/server.xml` file and add the attribute `URIEncoding="UTF-8"` to HTTP and AJP connectors that use
`redirectPort=8443`. Here are examples:


.Original server.xml
[source,xml]
----
<Connector port="8080" protocol="HTTP/1.1" connectionTimeout="20000" redirectPort="8443" />
...
<Connector port="8009" protocol="AJP/1.3" redirectPort="8443" />
----


.NEW server.xml
[source,xml]
----
<Connector port="8080" protocol="HTTP/1.1" connectionTimeout="20000" redirectPort="8443" URIEncoding="UTF-8" />
...
<Connector port="8009" protocol="AJP/1.3" redirectPort="8443" URIEncoding="UTF-8" />
----

=== Set executable flag

If you're on Unix, Linux, or Mac OS, make the shell scripts in your `$CATALINA_HOME/bin` and `$CATALINA_BASE/bin` folders executable by running
this command in each folder:

    chmod a+x *.sh

=== Checkpoint

Your application server is configured to run @product@.

. The file encoding, user time-zone, and preferred protocol stack are set in `setenv.sh`.
. The default memory available and Metaspace limit are set.
. `$CATALINA_BASE/conf/Catalina/localhost/ROOT.xml` declares the web application context.
. The `common.loader` property in `$CATALINA_BASE/conf/catalina.properties` grants Catalina access to the JARs in `$CATALINA_BASE/lib/ext`.
. `$CATALINA_BASE/conf/server.xml` sets UTF-8 encoding.
. The scripts in Tomcat's `bin` folders are executable.

== Setup

Follow the steps in the link:#_initial_setup[Initial setup] section.

== Deploying @product@

. Delete the contents of the `$CATALINA_BASE/webapps/ROOT` folder. This removes
the default Tomcat home page.
. Extract the @product@ `.war` file to `$CATALINA_BASE/webapps/ROOT`.

. Start Tomcat by navigating to `$CATALINA_HOME/bin` and executing
`./startup.sh`. Alternatively, execute `./catalina.sh run` to tail
@product@'s log file. The log audits startup activities and is useful for
debugging deployment.

====
After deploying @product@, you may see excessive warnings and log messages, such
as the ones below, involving `PhaseOptimizer`. These are benign and can be
ignored. Make sure to adjust your app server's logging level or log filters to
avoid excessive benign log messages.

    May 02, 2018 9:12:27 PM com.google.javascript.jscomp.PhaseOptimizer$NamedPass process
    WARNING: Skipping pass gatherExternProperties
    May 02, 2018 9:12:27 PM com.google.javascript.jscomp.PhaseOptimizer$NamedPass process
    WARNING: Skipping pass checkControlFlow
    May 02, 2018 9:12:27 PM com.google.javascript.jscomp.PhaseOptimizer$NamedPass process
    INFO: pass supports: [ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma, array pattern rest, arrow function, binary literal, block-scoped function declaration, class, computed property, const declaration, default parameter, destructuring, extended object literal, for-of loop, generator, let declaration, member declaration, new.target, octal literal, RegExp flag 'u', RegExp flag 'y', rest parameter, spread expression, super, template literal, modules, exponent operator (**), async function, trailing comma in param list]
    current AST contains: [ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma, array pattern rest, arrow function, binary literal, block-scoped function declaration, class, computed property, const declaration, default parameter, destructuring, extended object literal, for-of loop, generator, let declaration, member declaration, new.target, octal literal, RegExp flag 'u', RegExp flag 'y', rest parameter, spread expression, super, template literal, exponent operator (**), async function, trailing comma in param list, object literals with spread, object pattern rest]
====