= Installing @product@ bundle 

A @product@ bundle is an application server
with @product@ pre-installed. Using a bundle is the easiest way to install
@product@. @product@ is bundled with a number of application servers; all you need
to do is choose the one that best fits your needs. If you don't currently have
an application server preference, consider starting with the Tomcat bundle.
Tomcat is one of the most lightweight and straightforward bundles to configure.
If you have an open source application server preference, choose the server you
prefer from the available @product@ bundles. You must have a JDK (Java
Development Kit) installed prior to launching @product@.

[NOTE]
====
@product@ is not able to provide application server bundles for
proprietary application servers such as WebLogic or WebSphere, because the
licenses for these servers don't allow for redistribution. @product@'s commercial
offering, however, runs just as well on these application servers as it does on
the others. You'll need to follow our manual installation procedure using a
`.war` file to install @product@ on proprietary application servers.
====

You can download @product@ bundle with Tomcat from https://www.liferay.com/downloads-community

Getting a @product@ bundle up and running involves uncompressing the archive,
possibly copying a JDBC driver, and then starting the application server. 

[NOTE]
====
If you're using a non-supported database copy your
database's JDBC driver `.jar` file to `[Tomcat]/lib/ext` folder.
====

That's it! You've extracted @product@, and it's ready for use. This is much
easier than doing a manual installation on an app server. 

== Folder structure

@product@ bundles contain the same folder structure regardless of application
server. The top-level folder is named for the @product@ release. This folder is
called _Liferay Home_. This folder is usually the  application server's parent
folder. This is why @product@ bundles place the application server inside the
bundle's root folder. On a manual installation, the location of this folder
varies by application server. In a bundle, it's part of the bundle. If you're
doing a manual installation, please refer to the article covering that app
server for its location.

Liferay Home has folders for various purposes:

* *[Liferay Home]*
 ** *[Application Server]*: The name of this folder varies depending on
the bundle you're using. This folder contains the application server in
which @product@ has been installed.
 ** `data`: Stores an embedded HSQL database, @product@'s file repository,
and @product@'s search indexes. @product@ is initially configured to use
the embedded HSQL database but the HSQL database is primarily intended
for demonstration and trial purposes.
link:@platform-ref@/7.0/propertiesdoc/portal.properties.html#JDBC[Portal property `jdbc.default.url`]
sets the Hypersonic embedded HSQL database location.
 ** `deploy`: To auto-deploy @product@ plugins, copy them to this folder.
Legacy style `.war` files, @product-ver@ style `.jar` files, and `.lpkg`
files from Liferay Marketplace are supported.
link:@platform-ref@/7.0/propertiesdoc/portal.properties.html#Auto%20Deploy[Portal property `auto.deploy.deploy.dir`]
sets the auto-deploy location.
 ** `license`: @product@'s copyright and version files are here.
 ** `logs`: This folder contains @product@'s log files. The information in
@product@'s log files can be quite valuable for system administrators,
especially when trying to diagnose a problem. ``portal-impl.jar``'s
`portal-impl/src/META-INF/portal-log4j.xml` file sets the location for
the log files. To override the log file location, you must
link:/develop/tutorials/-/knowledge_base/7-0/advanced-customization-with-ext-plugins#using-advanced-configuration-files[use an `ext-impl/src/META-INF/portal-log4j-ext.xml` file in an Ext plugin].
 ** `osgi`: All the JAR files and a few configuration files for @product@'s
OSGi runtime belong in this folder.
link:@platform-ref@/7.0/propertiesdoc/portal.properties.html#Module%20Framework[Portal property `module.framework.base.dir`]
sets the OSGi folder location. Here are its subfolders:
  *** `configs`: Component configuration files go here
  *** `core`: @product@'s core modules
  *** `marketplace`: Marketplace applications and application suites
  *** `modules`: Modules you've deployed
  *** `portal`: @product@'s non-core modules
  *** `state`: Contains OSGi internal state files for such things as OSGi
bundle installation, bundle storage, and more
  *** `target-platform`: Target platform index
  *** `test`: Modules that support test integration
  *** `war`: WAR plugins you've deployed
 ** `patching-tool`: (Liferay DXP only) This folder
contains patches for @product@ and files for installing the patches.
 ** `tools`: For @product@ upgrade and target platform indexer.
 ** `work`: Module Jasper work files.

If @product@ is unable to create the resources it needs in the Liferay Home
folder or if it finds itself running on certain application servers, it creates
a folder called `liferay` in the home folder of the operating system user that
is running @product@. In this case, the `liferay` folder becomes Liferay Home.
For example, if the operating system user's name is jbloggs, the Liferay Home
folder is `/home/jbloggs/liferay` or `C:\Users\jbloggs\liferay`.