= @product@ Knowledge Base
Liferay's Knowledge Management Team and contributors
7.1, 2018.10.07
:toc: left

Welcome to the @product@ knowledge base. The knowledge base for @product@ is split into two sections.

== Documentation

This section contains information about all of the @product@'s features. It expleains how they are designed and how they are meant to be used.

* link:Documentation/User[User documentation]
* link:Documentation/DevOps[DevOps documentation]

== Tutorials

This section contains practical tutorials explaining how to achieve a desired result step by step

=== User Management

* How to customize the login screen
* How to add social login
* ...

=== Deployment

* How to install @prodcut@ on AWS
* How to install @prodcut@ on OpenShift
* ...

=== Tools

* How to configure Eclipse
* How to configure IntelliJ IDEA
* ...

=== ...

* ...
* ...
* ...



== Tools

This section provides information about the tools that make it easier to work with the portal

=== Build tools

* Blade and Workspace
* Maven
* Gradle
* NPM
* ...

=== Other tools

* Database upgrade
* ...


== Related technologies 

This section provides information about 3rd party technologies used in @product@ :

=== Technologies

* Portlet
* OSGi
* Spring
* ...

=== Products

* link:Related/Elasticsearch[Elasticsearch]
* link:Related/Solr[Solr]
* ...

== Extensions

This section provides information about extensions of the @product@ available on http://liferay.com/marketplace[Marketplace] or via other channels.

=== Markeplace apps

* Audience targeting
* Liferay Push 
* SAML connector
* ...

=== Products  
* Commerce
* Analytics Cloud
* DXP Cloud
* ... 




