= Mail server

Some functionalities of @product@, such as notifications, password reminders, ... use SMTP to send mail. 
For this functionalities to work, @product@ needs to be connected to mail server.

== Configuration via properties

Mail server access can be configured in `portal-ext.properties` file, useing the following properties 
_(customize their values for your environment)_:

    mail.session.mail.pop3.host=localhost
    mail.session.mail.pop3.password=
    mail.session.mail.pop3.port=110
    mail.session.mail.pop3.user=
    mail.session.mail.smtp.auth=false
    mail.session.mail.smtp.host=localhost
    mail.session.mail.smtp.password=
    mail.session.mail.smtp.port=25
    mail.session.mail.smtp.user=
    mail.session.mail.store.protocol=pop3
    mail.session.mail.transport.protocol=smtp

== Configuration via JNDI

Mail server access can be configured in the application server's mail session. In this case
the `portal-ext.properties` should contain the following property pointing to valid JNDI name:

    mail.session.jndi.name=mail/MailSession

== Configuration via UI

Mail server access can be configured in the UI by administrators. 
Configuration screen is available in `Control Panel` &rarr; `Server Administration` &rarr; `Mail`.

The form asks for the following information:

|===
| *Incoming POP Server:* | The hostname for a server running the Post Office Protocol. @product@ checks this mailbox for incoming messages, such as message board replies.
| *Incoming Port:* | The port on which the POP server is listening.
| *Use a Secure Network Connection:* | Use an encrypted connection when connecting to the POP server.
| *User Name:* | The user ID @product@ should use to log into the POP server.
| *Password:* | The password @product@ should use to log into the POP server.
| *Outgoing SMTP Server:* | The hostname for a server running the Simple Mail Transfer Protocol. @product@ uses this server to send emails, such as password change emails and other notifications.
| *Outgoing Port:* | The port on which the SMTP server is listening.
| *Use a Secure Network Connection:* |Use an encrypted connection when connecting to the SMTP server.
| *User Name:* | The user ID @product@ should use to log into the SMTP server.
| *Password:* | The password @product@ should use to log into the SMTP server.
| *Manually specify additional JavaMail properties to override the above configuration:* | If there are additional properties you need to specify supply them here.
|===


